### ISSUE TITLE
Some genera seem to be missing

### ISSUE THREAD

**Issue by MarinaGolivets** [idiv-biodiversity/lcvplants#25]
Taxa in the genera Centaurea, Senecio, Juncus, and some other seem to absent from the taxonomy, or at least they don't get matched using the LCVP function.

**Comment by alegent** [comment]
Please provide the list of the missing taxa. 
Thank you very much for your feedback.

**Comment by MarinaGolivets** [comment]
Please see the list of the taxa here:
[taxa_missing.txt](https://github.com/idiv-biodiversity/lcvplants/files/5787691/taxa_missing.txt)

When I was trying to match these names, I was getting the following error message:
"Error in if (LCVP_genus == genus) { : 
  missing value where TRUE/FALSE needed
"

**Comment by alegent** [comment]
here there is the result from LCVP applied to your list. It is absolutely possible not to be able to find some name in the LCVP list.

[LCVP_results_20210108_154311_ANSI.xlsx](https://github.com/idiv-biodiversity/lcvplants/files/5788045/LCVP_results_20210108_154311_ANSI.xlsx)

In the matched tab if there are more than one result for a taxon, this because you have specified the authority and the LCVP func. found more records with the same authority (e.g. Juncus articulatus L.) or it was not able to find the correct authority (e.g. Senecio ovatus (G.Gaertn.; B.Mey. & Scherb.) Hoppe) . If you want to have only one result from each name try to submit the list without the authority.

If you need more details about the missing names try to contact Martin Freiberg (https://biologie.lw.uni-leipzig.de/institut/ag/spezbot/mitarbeiterinnen/martin-freiberg/) author of the LCVP list.

Cheers

**Comment by MarinaGolivets** [comment]
Thank you for providing the results of the matching. For some reason, when I apply the function LCVP to those specific taxa, I get nothing (an empty tibble), regardless of whether I provide the authorship or not. For the other ca. 6k taxa, the function works just fine. 

For example:

lcvplants::LCVP("Centaurea calcitrapa", genus_search = T)
serial path, for searching a single taxon
Search based on genus and epithet name
Error in if (LCVP_genus == genus) { : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In strsplit(LCVPspecies_table[i, 1], " ") :
  input string 1 is invalid in this locale
2: In strsplit(LCVPspecies_table[i, 1], " ") :
  input string 1 is invalid in this locale

**Comment by alegent** [comment]
In my pc it works fine, are you using a linux/mac system? Try to remove and re-install the package.
Cheers

**Comment by MarinaGolivets** [comment]
I am using Mac. I tried installing and re-installing on two different Mac machines and still run into the same problem.
